language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - LD_LIBRARY_PATH=/usr/local/lib

install:
  - sudo apt-get update -qq
  - sudo apt-get install libxxf86vm-dev libosmesa6-dev
  - ./travis-install-assimp.sh

before_script:
  - rustc -V
  - cargo -V
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script: |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
